name: Deploy Virtual Machine with Kubevirt on AWS

on:
  push:
    branches:
      - main      # Trigger on pushes to the main branch

jobs:
  deploy-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy VM definition in kubevirt
        run: |
          kubectl apply -f vm.yaml  # Apply the virtual machine definition
          virtctl start testvm  # Start the VM
          kubectl get vmi testvm  # Verify the VM is running